csv:
  file-name: /questions
  file-extension: csv

exam:
  min-points: 3

project:
  version: @project.version@

spring:
  messages:
    basename: l10n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  main:
    allow-circular-references: true
