version: '3'
services:
  web:
    build: . 
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library
      - SPRING_DATASOURCE_USERNAME=java_app
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
    depends_on:
      - db
    expose:
      - 8080
  db:
    image: postgres
    environment:
      - POSTGRES_USER=java_app
      - POSTGRES_PASSWORD=Qwerty123
      - POSTGRES_DB=library
    ports:
      - "5432:5432"
    expose:
      - 5432