spring:
  main:
    allow-circular-references: true
  shell:
    interactive:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.nosql.mongock.changelog