DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
-- DROP TABLE IF EXISTS BOOKS_GENRES;
CREATE TABLE BOOKS(id BIGINT PRIMARY KEY, title VARCHAR(255), authorId BIGINT, genreId BIGINT);
CREATE TABLE AUTHORS(id BIGINT PRIMARY KEY, fullName VARCHAR(255));
CREATE TABLE GENRES(id BIGINT PRIMARY KEY, name VARCHAR(255));
-- CREATE TABLE BOOKS_GENRES(ID BIGINT PRIMARY KEY, name VARCHAR(255));