spring:
    datasource:
        url: jdbc:h2:mem:management
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    h2:
        console:
            enabled: true
    sql:
        init:
            mode: always
            data-locations: classpath:data.sql
            schema-locations: classpath:schema.sql
server:
    port: 36287
