drop table if exists orders CASCADE;

drop table if exists status CASCADE;

create table orders (
                        id bigint generated by default as identity,
                        status_id bigint,
                        primary key (id)
);

create table statuses (
                        dtype varchar(31) not null,
                        id bigint generated by default as identity,
                        name varchar(255),
                        primary key (id)
);

alter table orders
    add constraint FKnoettwqr56yaai4i8nwxg4huo
        foreign key (status_id)
            references statuses;